[mongodb]
mongodb.bhargavi.xyz

[catalogue]
172.31.16.57

[redis]
catalogue.bhargavi.xyz

[user]
catalogue.bhargavi.xyz

[cart]
catalogue.bhargavi.xyz

[frontend]
catalogue.bhargavi.xyz

[rabbitmq]
catalogue.bhargavi.xyz