[mongodb]
mongodb.bhargavi.xyz

[catalogue]
catalogue.bhargavi.xyz

[redis]
catalogue.bhargavi.xyz

[user]
catalogue.bhargavi.xyz

[cart]
catalogue.bhargavi.xyz

[frontend]
catalogue.bhargavi.xyz

[rabbitmq]
catalogue.bhargavi.xyz